Feature/crud
beaudible/vidyarthimgmt pull request #6
Opened 2023-08-08 11:19 UTC by 27Shubhi

2023-08-09 05:35 UTC, repoexplorer requested changes

2023-08-09 05:35 UTC, repoexplorer commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +public class VidyarthiRestController {
Rename this to VidyarthiController.

2023-08-09 05:35 UTC, repoexplorer commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +    //inject employee dao
Add javadoc comments not single line

2023-08-09 05:35 UTC, repoexplorer commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +    //add mapping for GET
same here

2023-08-09 05:35 UTC, repoexplorer commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +    private VidyarthiService vidyarthiService;
Add @Autowired here and remove manual constructor injection

2023-08-09 05:35 UTC, repoexplorer commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +    public VidyarthiRestController(VidyarthiService theVidyarthiService) {
Not needed, please remove

2023-08-09 05:35 UTC, repoexplorer commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +    public List<Vidyarthi> findAll() {
Fix url, and return ResponseEntity instead of core objects

2023-08-09 05:35 UTC, repoexplorer commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +    public Vidyarthi getVidyarthi(@PathVariable int vidyarthiId) {
Fix URL. and return ResponseEntity and do not use Entity object as dto

2023-08-09 05:35 UTC, repoexplorer commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +            throw new RuntimeException("id not found");
throw custom exceptions

2023-08-09 05:35 UTC, repoexplorer commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +    //add mapping for POST
Use javadoc comments

2023-08-09 05:35 UTC, repoexplorer commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +    public Vidyarthi addVidyarthi(@RequestBody Vidyarthi theVidyarthi) {
use ResponseEntity and use dto object

2023-08-09 05:35 UTC, repoexplorer commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +        theVidyarthi.setId(0);
What is this garbage

2023-08-09 05:35 UTC, repoexplorer commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +    public String deleteVidyarthi(@PathVariable int vidyarthiId) {
Same fixes as above and do not return String

2023-08-09 05:35 UTC, repoexplorer commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +        return ""+vidyarthiId;
don't use string literal

2023-08-09 05:35 UTC, repoexplorer commented on src/main/java/com/valmiki/vidyarthimgmt/entity/Vidyarthi.java
> +import jakarta.persistence.*;
Don't use *

2023-08-09 05:35 UTC, repoexplorer commented on src/main/java/com/valmiki/vidyarthimgmt/dao/VidyarthiDAOImpl.java
> +    private EntityManager entityManager;
Do not use EntityManager

2023-08-14 07:18 UTC, 27Shubhi commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +public class VidyarthiRestController {
done

2023-08-14 07:18 UTC, 27Shubhi commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +    //inject employee dao
done

2023-08-14 07:18 UTC, 27Shubhi commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +    //add mapping for GET
done

2023-08-14 07:18 UTC, 27Shubhi commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +    private VidyarthiService vidyarthiService;
done

2023-08-14 07:19 UTC, 27Shubhi commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +    public VidyarthiRestController(VidyarthiService theVidyarthiService) {
done

2023-08-14 07:19 UTC, 27Shubhi commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +        theVidyarthi.setId(0);
done

2023-08-14 07:19 UTC, 27Shubhi commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +    public String deleteVidyarthi(@PathVariable int vidyarthiId) {
done

2023-08-14 07:19 UTC, 27Shubhi commented on src/main/java/com/valmiki/vidyarthimgmt/controller/VidyarthiRestController.java
> +        return ""+vidyarthiId;
done

2023-08-14 07:19 UTC, 27Shubhi commented on src/main/java/com/valmiki/vidyarthimgmt/entity/Vidyarthi.java
> +import jakarta.persistence.*;
done

2023-08-14 07:19 UTC, 27Shubhi commented on src/main/java/com/valmiki/vidyarthimgmt/dao/VidyarthiDAOImpl.java
> +    private EntityManager entityManager;
fixed

2023-08-14 11:18 UTC, repoexplorer commented on src/main/java/com/valmiki/vidyarthimgmt/exception/VidyarthiAdvice.java
> +        };
Why semicolon

2023-08-14 11:32 UTC, repoexplorer approved these changes
LGTM

2023-08-14 11:32 UTC, merged